### PR TITLE
Update the README with the cool, new project name

### PR DESCRIPTION
**Pull request by MrPowers**

### CODE REVIEW

**Comment by MrPowers** [comment]
IntelliJ got rid of the `spark-func-extras.iml` file for me... let me know if you want it added back in.

**Comment by yaooqinn** [comment]
let's remove it, and I guess we should update the dependency in pom too

**Comment by yaooqinn** [comment]
In this repo, we usually add functions w/ spark `code-gen` support if appropriate.  Users might know that would help improve the performance

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
You can commit this PR of your own, and let's see if have proper authorities

**Comment by MrPowers** [comment]
@yaooqinn - Yep, was able to merge this in 😎 

I'll work on getting this running on my local machine and then add some examples to the README.

Then we can get this published and start marketing it to get users!

**Comment by yaooqinn** [comment]
awsome!

**Pull request merged**
